### ISSUE TITLE
Nav bar and buttons have stopped working

### ISSUE THREAD

**Issue by glynnbird** [IBM/carbon-hugo-theme#1]
I have a Hugo blog using this template and it has suddenly stopped working properly. There are no browser errors but the top bar buttons no longer work and appear styled incorrectly. Also other in-page buttons no longer display properly.

I've tried this with a freshly downloaded copy of this repo:

These two items used to be buttons:

<img width="356" alt="Screenshot 2024-02-01 at 13 02 27" src="https://github.com/IBM/carbon-hugo-theme/assets/697925/14b9fd88-de38-4046-87db-c3cda9e7bd58">

The word "Read" used to be a button that linked to a different page, and now isn't a button and isn't a link:

<img width="406" alt="Screenshot 2024-02-01 at 13 03 39" src="https://github.com/IBM/carbon-hugo-theme/assets/697925/a74e55e5-7e5f-4e8d-b826-248bc28995d1">

**Comment by rickymoorhouse** [comment]
Hi @glynnbird - I saw the same on the sites I am using this on and am investigating - it looks like there could be some changes to the carbon design system CDN files - so looking at what it takes to update to the latest copies or if I can get things working again quicker by pointing to a specific prior version

**Comment by glynnbird** [comment]
Thanks @rickymoorhouse 👍

**Comment by rickymoorhouse** [comment]
This should now be fixed in the main branch of the theme so if you pull in the latest it should work again

**Comment by glynnbird** [comment]
Confirmed it works and after a rebuild, the site now renders properly. I'm good to close this issue.

**Comment by rickymoorhouse** [comment]
Great thanks for the confirmation!
